// This file is automatically generated. Do not edit it directly.

const API_URL = (import.meta.env.VITE_API_URL as string | undefined) || '/api';
const STORAGE_BASE = API_URL.startsWith('http') ? API_URL.replace(/\/api$/, '') : '';
const TOKEN_KEY = 'krg_local_auth_token';

const listeners = new Set<(event: string, session: any) => void>();

const readToken = () => localStorage.getItem(TOKEN_KEY);
const writeToken = (token: string | null) => {
  if (token) localStorage.setItem(TOKEN_KEY, token);
  else localStorage.removeItem(TOKEN_KEY);
};

async function apiFetch(path: string, init: RequestInit = {}) {
  const token = readToken();
  const headers = new Headers(init.headers || {});
  if (!headers.has('Content-Type') && !(init.body instanceof FormData)) {
    headers.set('Content-Type', 'application/json');
  }
  if (token) headers.set('Authorization', `Bearer ${token}`);

  const response = await fetch(`${API_URL}${path}`, {
    ...init,
    headers,
  });
  const payload = await response.json().catch(() => ({}));

  if (!response.ok) {
    return { data: null, error: payload.error || { message: 'Erro na API local.' }, count: null };
  }

  return { ...payload, error: payload.error || null };
}

async function emitAuth(event: string) {
  const { data } = await auth.getSession();
  listeners.forEach((listener) => listener(event, data.session));
}

class QueryBuilder {
  table: string;
  operation: 'select' | 'insert' | 'update' | 'delete' | 'upsert' = 'select';

  filters: any[] = [];
  payload: any = null;
  orderBy: { column: string; ascending?: boolean } | null = null;
  limitValue: number | null = null;
  columns = '*';
  options: any = {};
  expect: 'many' | 'single' | 'maybeSingle' = 'many';

  constructor(table: string) {
    this.table = table;
  }

  select(columns = '*', options = {}) {
    this.columns = columns;
    this.options = { ...this.options, ...options };
    return this;
  }

  insert(values: any) {
    this.operation = 'insert';
    this.payload = values;
    return this;
  }

  upsert(values: any, options = {}) {
    this.operation = 'upsert';
    this.payload = values;
    this.options = { ...this.options, ...options };
    return this;
  }

  update(values: any) {
    this.operation = 'update';
    this.payload = values;
    return this;
  }

  delete() {
    this.operation = 'delete';
    return this;
  }

  eq(column: string, value: any) { this.filters.push({ type: 'eq', column, value }); return this; }
  is(column: string, value: any) { this.filters.push({ type: 'eq', column, value }); return this; }
  neq(column: string, value: any) { this.filters.push({ type: 'neq', column, value }); return this; }
  gt(column: string, value: any) { this.filters.push({ type: 'gt', column, value }); return this; }
  gte(column: string, value: any) { this.filters.push({ type: 'gte', column, value }); return this; }
  lt(column: string, value: any) { this.filters.push({ type: 'lt', column, value }); return this; }
  lte(column: string, value: any) { this.filters.push({ type: 'lte', column, value }); return this; }
  in(column: string, value: any[]) { this.filters.push({ type: 'in', column, value }); return this; }
  match(value: Record<string, any>) { this.filters.push({ type: 'match', value }); return this; }
  order(column: string, options = { ascending: true }) { this.orderBy = { column, ascending: options.ascending }; return this; }
  limit(limit: number) { this.limitValue = limit; return this; }
  single() { this.expect = 'single'; return this; }
  maybeSingle() { this.expect = 'maybeSingle'; return this; }

  async execute() {
    if (this.operation === 'select') {
      const result = await apiFetch('/db/query', {
        method: 'POST',
        body: JSON.stringify({
          table: this.table,
          filters: this.filters,
          order: this.orderBy,
          limit: this.limitValue,
          columns: this.columns,
          options: this.options,
        }),
      });
      if (result.error) return result;
      const rows = result.data || [];
      if (this.expect === 'single') return { data: rows[0] ?? null, error: rows[0] ? null : { message: 'Registro não encontrado.' }, count: result.count ?? null };
      if (this.expect === 'maybeSingle') return { data: rows[0] ?? null, error: null, count: result.count ?? null };
      return { data: rows, error: null, count: result.count ?? null };
    }

    const result = await apiFetch('/db/mutate', {
      method: 'POST',
      body: JSON.stringify({
        table: this.table,
        action: this.operation,
        values: this.payload,
        filters: this.filters,
        options: this.options,
      }),
    });
    if (result.error) return result;
    const rows = result.data || [];
    if (this.expect === 'single') return { data: rows[0] ?? null, error: rows[0] ? null : { message: 'Registro não encontrado.' } };
    if (this.expect === 'maybeSingle') return { data: rows[0] ?? null, error: null };
    return { data: rows, error: null };
  }

  then<TResult1 = any, TResult2 = never>(
    onfulfilled?: ((value: any) => TResult1 | PromiseLike<TResult1>) | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | null,
  ): Promise<TResult1 | TResult2> {
    return this.execute().then(onfulfilled, onrejected);
  }
}

const auth = {
  async getSession() {
    const result = await apiFetch('/auth/session', { method: 'GET' });
    return { data: { session: result.session || null }, error: result.error || null };
  },
  async getUser() {
    const sessionRes = await this.getSession();
    return { data: { user: sessionRes.data.session?.user || null }, error: sessionRes.error || null };
  },
  async signInWithPassword({ email, password }: { email: string; password: string }) {
    const result = await apiFetch('/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) });
    if (!result.error && result.token) writeToken(result.token);
    await emitAuth('SIGNED_IN');
    return { data: { session: result.user ? { user: result.user } : null, user: result.user || null }, error: result.error || null };
  },
  async signUp({ email, password, options }: { email: string; password: string; options?: any }) {
    const result = await apiFetch('/auth/register', { method: 'POST', body: JSON.stringify({ email, password, name: options?.data?.full_name || '' }) });
    if (!result.error && result.token) writeToken(result.token);
    await emitAuth('SIGNED_IN');
    return { data: { session: result.user ? { user: result.user } : null, user: result.user || null }, error: result.error || null };
  },
  async signOut() {
    writeToken(null);
    await emitAuth('SIGNED_OUT');
    return { error: null };
  },
  async resetPasswordForEmail(email: string, _options?: any) {
    const result = await apiFetch('/auth/reset-password', { method: 'POST', body: JSON.stringify({ email }) });
    return { data: result.data || null, error: result.error || null };
  },
  async updateUser(update: { password?: string; data?: Record<string, any> }) {
    if ((update as any).password) {
      const result = await apiFetch('/auth/update-password', { method: 'POST', body: JSON.stringify({ password: (update as any).password }) });
      return { data: result.data || null, error: result.error || null };
    }
    return { data: { user: null }, error: null };
  },
  onAuthStateChange(callback: (event: string, session: any) => void) {
    listeners.add(callback);
    return { data: { subscription: { unsubscribe: () => { listeners.delete(callback); return; } } } };
  },
};

const functions = {
  async invoke(name: string, { body }: { body?: any } = {}) {
    if (name !== 'reports-aggregator') {
      return { data: null, error: { message: `Function ${name} não implementada localmente.` } };
    }
    const result = await apiFetch('/reports/aggregate', { method: 'POST', body: JSON.stringify(body || {}) });
    return { data: result.error ? null : result, error: result.error || null };
  },
};

const storage = {
  from(_bucket: string) {
    return {
      async upload(_path: string, file: File, _options?: any) {
        const token = readToken();
        const formData = new FormData();
        formData.append('file', file);
        const response = await fetch(`${API_URL}/storage/upload`, {
          method: 'POST',
          headers: token ? { Authorization: `Bearer ${token}` } : {},
          body: formData,
        });
        const data = await response.json().catch(() => ({}));
        return { data, error: response.ok ? null : data.error || { message: 'Falha no upload.' } };
      },
      getPublicUrl(path: string) {
        return {
          data: {
            publicUrl: path.startsWith('http')
              ? path
              : `${STORAGE_BASE}${path.startsWith('/') ? '' : '/uploads/'}${path.replace(/^uploads\//, '')}`,
          },
        };
      },
    };
  },
};

const rpc = async (name: string, params: any = {}) => {
  const result = await apiFetch(`/rpc/${name}`, { method: 'POST', body: JSON.stringify(params) });
  return { data: result.data || null, error: result.error || null };
};

const createChannel = (_name: string) => {
  const subscription = { unsubscribe: () => undefined };
  const channelApi = {
    on: (_event: string, _filter: any, _callback: () => void) => channelApi,
    subscribe: () => subscription,
  };
  return channelApi;
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = {
  auth,
  from: (table: string) => new QueryBuilder(table),
  functions,
  storage,
  rpc,
  channel: createChannel,
  removeChannel: (_channel: any) => undefined,
};